import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import BigButton from "@/components/ui/button";
import AddDialog from "@/components/addDialog";
import { useState } from "react";

export default function Home() {
  const [open, setOpen] = useState(false);
  const handleDialogOpen = () => setOpen(true);
  const handleDialogClose = () => setOpen(false);

  return (
    <>
      <Head>
        <title>Todo Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>Todo Manager</h1>
        <AddDialog open={open} handleClose={handleDialogClose} />
        <BigButton handleClick={handleDialogOpen}>Add Todo</BigButton>
      </div>
    </>
  );
}
